### ISSUE TITLE
Support multiple meta instances with same name

### ISSUE THREAD

**Issue by dspruell** [chrislee35/yaratool#3]
Python 2.7.13 (default, Dec 18 2016, 07:03:34)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
yaratool (0.0.5) (`yaratool.__version__: '0.0.1'`).

[sample_rules.txt](https://github.com/chrislee35/yaratool/files/1018011/sample_rules.txt)

YARA 3.5.0 (and earlier?) supports use of multiple metdata fields sharing the same name. Currently yaratool will store only the last defined instance of the meta in YaraRule, overwriting any others in the rule. For consideration this patch stores multiple metas of same name in a list for the YaraRule.metas dictionary but retains single metas as original values (string, boolean, integer). It may be a better approach to determine if storing all metas as lists makes sense, if it's in line with the spirit of the rules syntax.

```patch
--- yaratool/__init__.py.bak2       2017-05-21 22:42:20.000000000 -0700
+++ yaratool/__init__.py    2017-05-21 23:27:00.000000000 -0700
@@ -50,10 +50,16 @@
 
         self.metas = {}
         if ifmeta:
+            mstore = {}
             for item in re.split('\n+', metas):
-                if re.search('\w',item):
-                    k,v = re.split('\s*=\s*',item.strip(),maxsplit=1)
-                    self.metas[k] = v
+                if re.search('\w', item):
+                    k,v = re.split('\s*=\s*', item.strip(), maxsplit=1)
+                    v = v.strip('"')
+                    if not k in mstore:
+                        mstore[k] = []
+                    mstore[k].append(v)
+            for k in mstore.keys():
+                self.metas[k] = mstore[k][0] if len(mstore[k]) == 1 else mstore[k]
         if strings:
             strarr = re.split('\n+', strings)
             self.strings = []
```

Result:

```python
In [3]: rules = yaratool.split(open('sample_rules.txt', 'r').read())

In [4]: r = rules[0]

In [5]: r.metas['author']
Out[5]: ['Alice', 'Bob']

In [6]: r = rules[1]

In [7]: r.metas['author']
Out[7]: ['Mallory', 'Eve']

```

**Comment by chrislee35** [comment]
integrated and pushed.  Thanks!
