### ISSUE TITLE
Normalize YARA string and Boolean metas

### ISSUE THREAD

**Issue by dspruell** [chrislee35/yaratool#4]
Metadata stored in a rule such as:

`someval = true`

...are currently parsed as the string values `"true"` or `"false"`. Ideally these will be parsed in YaraRule to Python `True` or `False` Boolean values.

String metadata stored such as:

`someval = "foo"`

...are currently parsed as strings retaining the enclosing double quotes ( e.g. `'"foo"'` ). Ideally these would be stripped for the string to be stored as a normalized Python string.

Not sure if something like this works?

```patch
--- yaratool/__init__.py.bak       2017-05-22 15:40:34.000000000 -0700
+++ yaratool/__init__.py           2017-05-22 16:12:37.000000000 -0700
@@ -25,6 +25,8 @@
 import re
 import sys
 import hashlib
+from distutils.util import strtobool
+
 
 __author__ =  'python@chrislee.dhs.org'
 __version__ = "0.0.1"
@@ -54,7 +56,10 @@
             for item in re.split('\n+', metas):
                 if re.search('\w', item):
                     k,v = re.split('\s*=\s*', item.strip(), maxsplit=1)
+                    # Strip quotes from values stored as YARA strings
+                    v = v.strip('"')
+                    # Metas stored as YARA booleans should be converted to Python bools
+                    if v in ('true', 'false'): v = bool(strtobool(v))
                     if not k in mstore:
                         mstore[k] = []
                     mstore[k].append(v)

```

**Comment by chrislee35** [comment]
I went in and hacked a bunch more types, bools, ints, floats, and the like.  I also fixed the output section.  Version 0.0.7 should address all these.
